# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-13 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='EntradaHorari',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extHoraris.Aula')),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extHoraris.Dia')),
            ],
            options={
                'verbose_name': "Entrada de l'horari",
            },
        ),
        migrations.CreateModel(
            name='Franja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcio', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Grup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('fusio', models.BooleanField()),
                ('nomFusio', models.CharField(blank=True, max_length=50)),
                ('codiXtec', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codi', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Profe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomUsuari', models.CharField(max_length=50)),
                ('nomComplert', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='entradahorari',
            name='franja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extHoraris.Franja'),
        ),
        migrations.AddField(
            model_name='entradahorari',
            name='grup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extHoraris.Grup'),
        ),
        migrations.AddField(
            model_name='entradahorari',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extHoraris.Materia'),
        ),
        migrations.AddField(
            model_name='entradahorari',
            name='profe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='extHoraris.Profe'),
        ),
        migrations.AlterUniqueTogether(
            name='entradahorari',
            unique_together=set([('materia', 'profe', 'grup', 'aula', 'dia', 'franja')]),
        ),
    ]
