# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-31 14:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnes', '0006_alumne_usuaris_app_associats'),
        ('presencia', '0005_auto_20180411_1945'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='controlassistencia',
            index_together=set([('alumne', 'estat', 'relacio_familia_notificada')]),
        ),
    ]
