# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-12 23:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presencia', '0006_nohadeseralaula_uf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nohadeseralaula',
            name='uf',
        ),
    ]
