# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-12 23:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignatures', '0003_uf_ufavisos'),
        ('presencia', '0007_remove_nohadeseralaula_uf'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlassistencia',
            name='uf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assignatures.UF'),
        ),
    ]
