# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-10 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumnes', '0007_alumne_municipi'),
        ('assignatures', '0002_tipusdassignatura_capcelera'),
    ]

    operations = [
        migrations.CreateModel(
            name='UF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=25)),
                ('dinici', models.DateTimeField()),
                ('dfi', models.DateTimeField()),
                ('horesTeoriques', models.IntegerField()),
                ('assignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignatures.Assignatura')),
            ],
        ),
        migrations.CreateModel(
            name='UFAvisos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nAvis', models.PositiveSmallIntegerField()),
                ('alumne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnes.Alumne')),
                ('assignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignatures.Assignatura')),
            ],
        ),
    ]
