# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-27 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignatures', '0003_uf_ufavisos'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignatura',
            name='activar_notificacions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignatura',
            name='percent_primer_avis',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='assignatura',
            name='percent_segon_avis',
            field=models.PositiveSmallIntegerField(default=15),
        ),
    ]
