# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-08 19:51
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('alumnes', '0005_auto_20171025_1830'),
        ('usuaris', '0002_professorconserge'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumnePortalUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('data_creacio', models.DateField(auto_now_add=True)),
                ('relacio_amb_l_alumne', models.CharField(blank=True, choices=[(b'PARE', b'Pare'), (b'MARE', b'Mare'), (b'ALTRES', b'Altres'), (b'APP', b'Usuari APP')], max_length=7)),
                ('alumne_relacionat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnes.Alumne')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PortalTokenUser',
            fields=[
                ('usuari_del_token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='portal_token_user_set', related_query_name='portal_token_user', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('data_creacio', models.DateField(auto_now_add=True)),
                ('clau', models.CharField(max_length=120)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PortalUser',
            fields=[
            ],
            options={
                'ordering': ['last_name', 'first_name', 'username'],
                'proxy': True,
                'indexes': [],
            },
            bases=('auth.user',),
        ),
        migrations.AddField(
            model_name='alumneportaluser',
            name='usuari_relacionat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumne_portal_user_set', related_query_name='alumne_portal_user', to='usuaris.PortalUser'),
        ),
    ]
