# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-29 19:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alumnes', '0005_auto_20171025_1830'),
        ('usuaris', '0002_professorconserge'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractQRPortal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moment_expedicio', models.DateTimeField(auto_now_add=True)),
                ('moment_captura', models.DateTimeField(blank=True, null=True, unique=True)),
                ('moment_confirmat_pel_tutor', models.DateTimeField(blank=True, null=True)),
                ('darrera_sincronitzacio', models.DateTimeField(blank=True, null=True)),
                ('novetats_detectades_moment', models.DateTimeField(blank=True, null=True)),
                ('clau', models.CharField(db_index=True, max_length=40)),
                ('localitzador', models.CharField(db_index=True, default=b'-', max_length=4, unique=True)),
                ('es_el_token_actiu', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='QRPortal',
            fields=[
                ('abstractqrportal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuaris.AbstractQRPortal')),
            ],
            bases=('usuaris.abstractqrportal',),
        ),
        migrations.AddField(
            model_name='abstractqrportal',
            name='alumne_referenciat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_portal_set', related_query_name='qr_portal', to='alumnes.Alumne'),
        ),
        migrations.AddField(
            model_name='abstractqrportal',
            name='usuari_referenciat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
