# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-08 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuaris', '0003_auto_20180508_1951'),
        ('alumnes', '0005_auto_20171025_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumne',
            name='usuaris_associats',
            field=models.ManyToManyField(blank=True, related_name='alumnes_associats', related_query_name='alumnes_associats', through='usuaris.AlumnePortalUser', to='usuaris.PortalUser'),
        ),
    ]
