# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-29 19:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuaris', '0003_auto_20180529_1943'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alumnes', '0005_auto_20171025_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumne',
            name='usuaris_app_associats',
            field=models.ManyToManyField(related_name='alumne_app_set', related_query_name='alumne_app', through='usuaris.QRPortal', to=settings.AUTH_USER_MODEL),
        ),
    ]
